export const CONTACTME_REQUEST = 'CONTACTME_REQUEST'
export const CONTACTME_SUCCESS = 'CONTACTME_SUCCESS'
export const CONTACTME_FAIL = 'CONTACTME_FAIL'
export const CONTACTME_RESET = 'CONTACTME_RESET'
