export const PERSONAL_INFO_REQUEST = "PERSONAL_INFO_REQUEST"
export const PERSONAL_INFO_SUCCESS = 'PERSONAL_INFO_SUCCESS'
export const PERSONAL_INFO_FAIL = "PERSONAL_INFO_FAIL"

export const TEAMS_REQUEST = 'TEAMS_REQUEST'
export const TEAMS_SUCCESS = 'TEAMS_SUCCESS'
export const TEAMS_FAIL = 'TEAMS_FAIL'

export const SERVICES_REQUEST = 'SERVICES_REQUEST'
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS'
export const SERVICES_FAIL = 'SERVICES_FAIL'

export const TEAMS_BG_REQUEST = 'TEAMS_BG_REQUEST'
export const TEAMS_BG_SUCCESS = 'TEAMS_BG_SUCCESS'
export const TEAMS_BG_FAIL = 'TEAMS_BG_FAIL'

export const SERVICES_BG_REQUEST = 'SERVICES_BG_REQUEST'
export const SERVICES_BG_SUCCESS = 'SERVICES_BG_SUCCESS'
export const SERVICES_BG_FAIL = 'SERVICES_BG_FAIL'


