export const PROJECTS_REQUEST = 'PROJECTS_REQUEST'
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS'
export const PROJECTS_FAIL = 'PROJECTS_FAIL'


export const PROJECT_BY_ID_REQUEST = 'PROJECT_BY_ID_REQUEST'
export const PROJECT_BY_ID_SUCCESS = 'PROJECT_BY_ID_SUCCESS'
export const PROJECT_BY_ID_FAIL = 'PROJECT_BY_ID_FAIL'