# Generated by Django 3.2.5 on 2022-07-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_auto_20220724_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'get_latest_by': ['_id']},
        ),
    ]
