# Generated by Django 3.2.5 on 2022-07-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_personalinfo_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'get_latest_by': ['created_at']},
        ),
    ]
