# Generated by Django 3.2.5 on 2022-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_alter_personalinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
