# Generated by Django 3.2.5 on 2022-07-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0008_personalinfo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='contactme',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
