# Generated by Django 4.1.1 on 2022-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0010_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBgImage',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsBgImage',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
